---
title: "Week8_Tako_101924"
author: "Abigail Tako"
date: "October 19, 2024"
format: html
---

## Project Presentation

### Brief explanation

|                                                                                                                                 |
|------------------------------------------------------------------------|
| The data set that we chose as a group is the **U.S. GDP attributed to for-hire transportation services between 1980 and 2022**. |

#### Variables

-   [Year]{.underline}

    The year for which the GDP data is recorded from 1980 to 2022.

-   [Air transportation]{.underline}

    GDP attributed to for-hire **air transportation services** (billions of current dollars).

-   [Rail transportation]{.underline}

    GDP attributed to for-hire **rail transportation services** (billions of current dollars).

-   [Water transportation]{.underline}

    GDP attributed to for-hire **water transportation services** (billions of current dollars).

-   [Truck transportation]{.underline}

    GDP attributed to for-hire **truck transportation services** (billions of current dollars).

-   [Transit and ground passenger transportation]{.underline}

    GDP attributed to for-hire **transit and ground passenger transportation services**, such as buses, taxis, etc. (billions of current dollars).

-   [Pipeline transportation]{.underline}

    GDP attributed to **pipeline transportation services**, which typically include transportation of natural gas and oil (billions of current dollars).

-   [Other transportation and support activities]{.underline}

    GDP attributed to **other transportation-related services**, including logistics support activities, courier services, etc. (billions of current dollars).

-   [Warehousing and storage]{.underline}

    GDP attributed to **warehousing and storage services**, which include storage of goods and inventory management (billions of current dollars).\

#### Purpose

Analyzing this data as a group can help:

-   improve the findings based on overall

-   to input necessary changes

-   make a solid and strong conclusion based on the findings from different perspectives of each of the member
